language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5
    - php: hhvm
  allow_failures:
    - php: hhvm

before_script:
  - composer update --prefer-dist

script:
  - ./vendor/bin/phpcs .
  - ./vendor/bin/phpunit

after_script:
  - php vendor/bin/php-coveralls -v
