language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: 5.5
        - php: 5.4
        - php: 5.3
        - php: hhvm



matrix:
  include:
    - php: 5.3
      dist: precise

before_script:
  - composer update --prefer-dist

after_script:
  - php vendor/bin/coveralls -v
