language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5
    - php: 5.4
    - php: hhvm
    - {php: 5.3, dist: precise}
  allow_failures:
    - php: 5.5
    - php: 5.4
    - php: 5.3
    - php: hhvm

before_script:
  - composer update --prefer-dist

after_script:
  - php vendor/bin/coveralls -v
